name: svf-teaching

# Triggers the workflow on push or pull request events
on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      # checkout the repo
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          
      # setup the environment
      - name: ubuntu-setup
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install cmake gcc g++ nodejs doxygen graphviz
          
      # install llvm and svf
      - name: env-setup
        run: |
          npm install svf-lib
          
      # build current repo
      - name: build-svf
        run: |
         source $GITHUB_WORKSPACE/env.sh
         cmake .
         make 
